<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cetak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cetak_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'cetak/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'cetak/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'cetak/index.html';
            $config['first_url'] = base_url() . 'cetak/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Cetak_model->total_rows($q);
        $cetak = $this->Cetak_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'cetak_data' => $cetak,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('cetak/cetak', $data);
    }
}
/* End of file Cetak.php */
/* Location: ./application/controllers/Cetak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-28 12:41:46 */
/* http://harviacode.com */