<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Regis extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Regis_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'regis/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'regis/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'regis/index.html';
            $config['first_url'] = base_url() . 'regis/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Regis_model->total_rows($q);
        $regis = $this->Regis_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'regis_data' => $regis,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('regis/regis_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Regis_model->get_by_id($id);
        if ($row) {
            $data = array(
		'no' => $row->no,
		'nama' => $row->nama,
	    );
            $this->load->view('regis/regis_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('regis'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('regis/create_action'),
	    'no' => set_value('no'),
	    'nama' => set_value('nama'),
	);
        $this->load->view('regis/regis_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
	    );

            $this->Regis_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('regis'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Regis_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('regis/update_action'),
		'no' => set_value('no', $row->no),
		'nama' => set_value('nama', $row->nama),
	    );
            $this->load->view('regis/regis_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('regis'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('no', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
	    );

            $this->Regis_model->update($this->input->post('no', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('regis'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Regis_model->get_by_id($id);

        if ($row) {
            $this->Regis_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('regis'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('regis'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');

	$this->form_validation->set_rules('no', 'no', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Regis.php */
/* Location: ./application/controllers/Regis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-11-05 05:02:34 */
/* http://harviacode.com */